home/urls.py
from django.urls import path

from .views import HomePage


app_name="home"
urlpatterns = [
    path('', HomePage.as_view(), name="home"),
]

journal/urls.py
from django.urls import path
from .views import JournalCreateView, JournalDeleteView, JournalDetailView, JournalListView, JournalUpdateView

app_name="journal"
urlpatterns = [
    path("", JournalListView.as_view(), name="list-journals"),
    path("create/", JournalCreateView.as_view(), name="create-journal"),
    path("update/<slug:slug>/", JournalUpdateView.as_view(), name="update-journal"),
    path("delete/<slug:slug>/", JournalDeleteView.as_view(), name="delete-journal"),
    path("<slug:slug>/", JournalDetailView.as_view(), name="journal-detail"),
]

journal/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.utils.text import slugify
from django.utils import timezone

User = settings.AUTH_USER_MODEL


class Journal(models.Model):
    """Model for representing a journal"""
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=False, blank=False, related_name="journals")
    name = models.CharField(_("Name of Journal"), max_length=50, help_text=_(
        "Enter the name you would like to give to your journal."), null=False, blank=False)
    slug = models.SlugField(max_length=50, default="", unique=True)
    description = models.TextField(_("Description"), max_length=100, help_text=_(
        "What is this journal about?"), null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    background_color = models.CharField(_("Background Color"), max_length=10, help_text=_(
        "Color to give to the background of the journal"))
    text_color = models.CharField(_("Text Color"),
        max_length=10, help_text=_("color to give the text"))

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("journal:journal-detail", kwargs={"slug": self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(f"{self.name}-{self.created}")
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ["-created"]
        verbose_name_plural = "Journals"

journal/forms.py
from django import forms
from django.forms import fields
from .models import Journal


class JournalCreateUpdateForm(forms.ModelForm):
    """Model to create or update a journal object"""

    class Meta:
        model = Journal
        fields = ["name", "description", "background_color", "text_color"]

journal/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import request
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import DeleteView, UpdateView

from journal.models import Journal

from .forms import JournalCreateUpdateForm


class JournalListView(LoginRequiredMixin, ListView):
    """View to list all journals"""
    template_name = "journal/list-journals.html"
    model = Journal
    context_object_name = "journals"

class JournalCreateView(LoginRequiredMixin, CreateView):
    """View to create a new journal object"""
    form_class = JournalCreateUpdateForm
    template_name = "journal/create-journal.html"
    success_url = reverse_lazy("journal:list-journals")

    def form_valid(self, form):
        journal = form.save(commit=False)
        journal.user = self.request.user
        journal.save()
        return super().form_valid(form)


class JournalDetailView(LoginRequiredMixin, DetailView):
    """View to show the detail of a particular journal"""
    template_name = "journal/journal-detail.html"
    model = Journal
    context_object_name = "journal"


class JournalUpdateView(LoginRequiredMixin, UpdateView):
    """view to update a particular journal"""
    model = Journal
    context_object_name = "journal"
    template_name = "journal/update-journal.html"
    form_class = JournalCreateUpdateForm
    success_url = reverse_lazy("journal:list-journals")


class JournalDeleteView(LoginRequiredMixin, DeleteView):
    model = Journal
    context_object_name = "journal"
    success_url = reverse_lazy("journal:list-journals")

    def get(self, request, *args, **kwargs):
        """ delete the journal object on a get request """
        return self.delete(request, *args, **kwargs)


# TODO - make the success_url of the create and update fields go to the individual journal page
# TODO - when the delete journal is clicked, bring a pop up modal for the user to confirm deletion, before you hit this endpoint

templates/journal/create-journal.html
{% extends 'dashboard/base.html' %}

{% block title %}Add new journal{% endblock title %}


{% block content %}

    <div class="flex justify-around" style="min-height: 80vh;">
        <div class="w-4/5 lg:w-3/5 self-center">
            <h1 class="text-3xl font-bold py-5 mt-7 text-center">Create a New Journal</h1>

            <div>
                {% if form.errors %}
                    <p>{{ form.errors }}</p>
                {% endif %}
            </div>

            <form method="POST">
                {% csrf_token %}
                <!-- Name of Journal -->
                <div class="flex flex-col my-4">
                    <label for="id_name" class="form-label-2">Name of Journal:</label> 
                    <input id="id_name" maxlength="50" name="name" required="" type="text" class="form-input-2 font-bold"/> 
                    <span class="form-helptext-1">Enter the name you would like to give to your journal.</span>
                </div>
                
                <!-- About of journal -->
                <div class="flex flex-col my-4">
                    <label for="id_description" class="form-label-2">Description:</label> 
                    <textarea cols="40" id="id_description" maxlength="100" name="description" rows="2" class="border-2 border-purple-600 focus:outline-none p-3"></textarea> 
                    <span class="form-helptext-1">What is this journal about?</span>
                </div>

               <div class="flex flex-col md:flex-row lg:flex-row md:space-x-4 my-4 bg-gray-300 p-5 rounded-md shadow-xl">
                    <!-- Background Color Picker of Journal -->
                    <div class="flex-1 flex flex-col">
                        <label for="id_background_color" class="form-label-2">Background Color:</label> 
                        <input id="id_background_color" maxlength="10" name="background_color" required="" type="text" class="form-input-2" style="display: none;"/> 
                        <input type="color" name="" class="h-12 w-full border-2 border-purple-600" id="id_background_color_picker" value="#000000">
                        <span class="form-helptext-1">journal background color</span>
                    </div>

                    <!-- Text Color Picker of Journal -->
                    <div class="flex-1 flex flex-col">
                        <label for="id_text_color" class="form-label-2">Text Color:</label> 
                        <input id="id_text_color" maxlength="10"  name="text_color" required="" type="text" class="form-input-2" style="display: none;"/> 
                        <input type="color" class="h-12 w-full border-2 border-purple-600" name="" id="id_text_color_picker" value="#ffffff">
                        <span class="form-helptext-1">journal name text color</span>
                    </div>
               </div>

               <div>
                   <button type="submit" class="px-4 font-bold py-3 bg-green-700 hover:bg-green-800 rounded-md text-white">Make Journal</button>
               </div>
            </form>
        </div>
    </div>

{% endblock content %}


{% block extra_js %}

<script>
    bgColorPicker = document.getElementById("id_background_color_picker");
    textColorPicker = document.getElementById("id_text_color_picker");
    
    bgColorInput = document.getElementById("id_background_color");
    textColorInput = document.getElementById("id_text_color");

    bgColorPicker.addEventListener("input", updateBgColor, false);
    textColorPicker.addEventListener("change", updateTextColor, false); 

    function updateBgColor() {
        bgColorInput.value = bgColorPicker.value;
    }

    function updateTextColor() {
        textColorInput.value = textColorPicker.value;
    }
</script>

{% endblock extra_js %}

templates/journal/journal-detail.html
{% extends 'dashboard/base.html' %}

{% block title %}{{ journal.name }}{% endblock title %}


{% block content %}

<div>
    <h1 class="font-bold text-3xl">{{ journal.name }}</h1>
    {{ journal.created }} <br />

    <a class="text-green-600 font-bold text-xl" href="{% url 'journal:update-journal' journal.slug %}">Update Journal</a> <br />

    <a class="text-red-600 font-bold text-xl" href="{% url 'journal:delete-journal' journal.slug %}">Delete Journal</a>
</div>

{% endblock content %}

templates/journal/list-journals.html
{% extends 'dashboard/base.html' %}

{% block title %}All Journals{% endblock %}


{% block content %}

<div>

    <h1 class="text-black text-center font-bold text-2xl">Your Journals</h1>

    {% for journal in journals %}
        <div>
            <h1 class="text-pink-600 text-lg"><a href="{{ journal.get_absolute_url }}">{{ journal.name }}</a></h1>
        </div>
    {% endfor %}

</div>

{% endblock content %}

templates/journal/update-journal.html
{% extends 'dashboard/base.html' %}

{% block title %}Update Journal - {{ journal.name }}{% endblock title %}


{% block content %}
    <div class="flex justify-around" style="min-height: 80vh;">
        <div class="w-4/5 lg:w-3/5 self-center">
            <h1 class="text-3xl font-bold py-5 mt-7 text-center">Update - {{ journal.name }}</h1>

            <div>
                {% if form.errors %}
                    <p>{{ form.errors }}</p>
                {% endif %}
            </div>

            <form method="POST">
                {% csrf_token %}
                <!-- Name of Journal -->
                <div class="flex flex-col my-4">
                    <label for="id_name" class="form-label-2">Name of Journal:</label> 
                    <input id="id_name" maxlength="50" name="name" required="" type="text" class="form-input-2 font-bold" value="{{ journal.name }}"/> 
                    <span class="form-helptext-1">Enter the name you would like to give to your journal.</span>
                </div>
                
                {% comment %} <!-- About of journal -->
                <div class="flex flex-col my-4">
                    <label for="id_description" class="form-label-2">Description:</label> 
                    <textarea cols="40" id="id_description" maxlength="100" name="description" rows="2" class="border-2 border-purple-600 focus:outline-none p-3">{{ journal.description }}</textarea> 
                    <span class="form-helptext-1">What is this journal about?</span>
                </div>
                {% endcomment %}

               <div class="flex flex-col md:flex-row lg:flex-row md:space-x-4 my-4 bg-gray-300 p-5 rounded-md shadow-xl">
                    <!-- Background Color Picker of Journal -->
                    <div class="flex-1 flex flex-col">
                        <label for="id_background_color" class="form-label-2">Background Color:</label> 
                        <input id="id_background_color" maxlength="10" name="background_color" required="" type="text" class="form-input-2" style="display: none;"/> 
                        <input type="color" name="" class="h-12 w-full border-2 border-purple-600" id="id_background_color_picker" value="{{ journal.background_color">
                        <span class="form-helptext-1">journal background color</span>
                    </div>

                    <!-- Text Color Picker of Journal -->
                    <div class="flex-1 flex flex-col">
                        <label for="id_text_color" class="form-label-2">Text Color:</label> 
                        <input id="id_text_color" maxlength="10"  name="text_color" required="" type="text" class="form-input-2" style="display: none;"/> 
                        <input type="color" class="h-12 w-full border-2 border-purple-600" name="" id="id_text_color_picker" value="{{ journal.text_color }}">
                        <span class="form-helptext-1">journal name text color</span>
                    </div>
               </div>

               <div>
                   <button type="submit" class="px-4 font-bold py-3 bg-green-700 hover:bg-green-800 rounded-md text-white">Update Journal</button>
               </div>
            </form>
        </div>
    </div>

{% endblock content %}


{% block extra_js %}

<script>
    bgColorPicker = document.getElementById("id_background_color_picker");
    textColorPicker = document.getElementById("id_text_color_picker");
    
    bgColorInput = document.getElementById("id_background_color");
    textColorInput = document.getElementById("id_text_color");

    bgColorPicker.addEventListener("input", updateBgColor, false);
    textColorPicker.addEventListener("change", updateTextColor, false); 

    function updateBgColor() {
        bgColorInput.value = bgColorPicker.value;
    }

    function updateTextColor() {
        textColorInput.value = textColorPicker.value;
    }
</script>

{% endblock extra_js %}

<!-- TODO - make sure that the update form works on a custom designed form -->