home/urls.py
from django.urls import path

from .views import HomePage


app_name="home"
urlpatterns = [
    path('', HomePage.as_view(), name="home"),
]

journal/urls.py
from django.urls import path
from .views import JournalCreateView, JournalDeleteView, JournalDetailView, JournalListView, JournalUpdateView

app_name="journal"
urlpatterns = [
    path("", JournalListView.as_view(), name="list-journals"),
    path("create/", JournalCreateView.as_view(), name="create-journal"),
    path("update/<slug:slug>/", JournalUpdateView.as_view(), name="update-journal"),
    path("delete/<slug:slug>/", JournalDeleteView.as_view(), name="delete-journal"),
    path("<slug:slug>/", JournalDetailView.as_view(), name="journal-detail"),
]

users/urls.py
from django.urls import path

from .views import UserProfileView

app_name="users"
urlpatterns = [
    path("profile/", UserProfileView.as_view(), name="user-profile")
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager


class CustomUserManager(BaseUserManager):
    """Custom user manager for the authentication and creation of user objects"""
    def create_user(self, email, password, **extra_fields):
        """Create user object with the given email and password"""
        if not email:
            raise ValueError("Email field is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """Create and save superuser object with email and password"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True'))
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """Custom user model for the project"""
    username = None
    email = models.EmailField(_("Email address"), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

users/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class UserProfileView(TemplateView):
    template_name = "users/profile.html"

templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/tailwind/tailwind.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <title>{% block title %}EasyJournal{% endblock title %}</title>
</head>
<body>

    {% block content %}{% endblock content %}
    
</body>
</html>

templates/users/profile.html
{% extends 'dashboard/base.html' %}
{% load account %}
{% user_display user %}

{% block title %}User Profile{% endblock title %}


{% block content %}

    <div class="">

        {% if messages %}
            <div>
                {% for message in message %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}

        <div>
            <h1 class="text-bold text-2xl">Profile</h1>
            <p>email: {{ user.email }}</p>
        </div>

        <a href="{% url 'account_logout' %}" class="link-1">LOGOUT</a> <br />
        <a href="{% url 'journal:create-journal' %}" class="link-1">Make Journal</a>
        <br />

        <a href="{% url 'journal:list-journals' %}" class="link-1">My Journals</a>
    </div>

    <div>

{% endblock content %}